#include <cstdio>

typedef int CUresult;

#define CUDA_ERROR_NOT_SUPPORTED 801



extern "C" {

__attribute__((visibility("default"))) CUresult cuArray3DCreate(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuArray3DGetDescriptor(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuArrayCreate(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuArrayGetDescriptor(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuArrayGetMemoryRequirements(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuArrayGetPlane(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuArrayGetSparseProperties(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuCtxCreate(void) { return CUDA_ERROR_NOT_SUPPORTED; }
extern "C" __attribute__((visibility("default"))) CUresult cuCtxGetApiVersion(void *ctx, unsigned int *version) { (void)ctx; if (version) *version = 3020; return 0; }
__attribute__((visibility("default"))) CUresult cuCtxGetCacheConfig(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuCtxGetFlags(void) { fprintf(stderr, "[COMPAT_STUB] cuCtxGetFlags CALLED\n");fflush(stderr);return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuCtxGetSharedMemConfig(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuCtxGetStreamPriorityRange(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuCtxResetPersistingL2Cache(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuCtxSetCacheConfig(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuCtxSetSharedMemConfig(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDestroyExternalMemory(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDestroyExternalSemaphore(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDeviceGetByPCIBusId(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDeviceGetDefaultMemPool(void) { fprintf(stderr, "[COMPAT_STUB] cuDeviceGetDefaultMemPool CALLED\n");fflush(stderr);return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDeviceGetGraphMemAttribute(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDeviceGetMemPool(void) { fprintf(stderr, "[COMPAT_STUB] cuDeviceGetMemPool CALLED\n");fflush(stderr);return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDeviceGetNvSciSyncAttributes(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDeviceGetP2PAttribute(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDeviceGetPCIBusId(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDeviceGetTexture1DLinearMaxWidth(void) { return CUDA_ERROR_NOT_SUPPORTED; }
// cuDeviceGetUuid[/_v2]: numba (used by cuDF via JIT) resolves this exported
// symbol directly and requires it to succeed to build the device identity for
// its context cache. The old (void)->NOT_SUPPORTED stub made numba's
// current_context() raise CudaAPIError(801); inside cuDF's background init
// thread that killed the thread -> its GVirtuS connection reset -> the main
// import cudf hung. Return a deterministic (zeroed) 16-byte UUID + SUCCESS:
// there is a single virtual device, so a constant identity is sufficient.
extern "C" __attribute__((visibility("default"))) CUresult cuDeviceGetUuid(void *uuid, int dev) { (void)dev; if (uuid) { for (int i = 0; i < 16; ++i) ((char *)uuid)[i] = 0; } return 0; }
extern "C" __attribute__((visibility("default"))) CUresult cuDeviceGetUuid_v2(void *uuid, int dev) { (void)dev; if (uuid) { for (int i = 0; i < 16; ++i) ((char *)uuid)[i] = 0; } return 0; }
__attribute__((visibility("default"))) CUresult cuDeviceGraphMemTrim(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDevicePrimaryCtxSetFlags(void) { fprintf(stderr, "[COMPAT_STUB] cuDevicePrimaryCtxSetFlags CALLED\n");fflush(stderr);return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDevicePrimaryCtxSetFlags_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDeviceRegisterAsyncNotification(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDeviceSetGraphMemAttribute(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDeviceSetMemPool(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDeviceTotalMem(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuDeviceUnregisterAsyncNotification(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuEGLStreamConsumerAcquireFrame(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuEGLStreamConsumerConnect(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuEGLStreamConsumerConnectWithFlags(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuEGLStreamConsumerDisconnect(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuEGLStreamConsumerReleaseFrame(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuEGLStreamProducerConnect(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuEGLStreamProducerDisconnect(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuEGLStreamProducerPresentFrame(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuEGLStreamProducerReturnFrame(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuEventDestroy(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuEventElapsedTime_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuEventRecord_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuEventRecordWithFlags(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuEventRecordWithFlags_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuExternalMemoryGetMappedBuffer(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuExternalMemoryGetMappedMipmappedArray(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuFlushGPUDirectRDMAWrites(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuFuncGetName(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuFuncGetParamInfo(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuFuncSetSharedMemConfig(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGetExportTable(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGetProcAddress(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGLCtxCreate(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGLCtxCreate_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGLGetDevices(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGLInit(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGLMapBufferObject(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGLMapBufferObjectAsync(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGLMapBufferObjectAsync_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGLMapBufferObjectAsync_v2_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGLMapBufferObject_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGLMapBufferObject_v2_ptds(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGLRegisterBufferObject(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGLSetBufferObjectMapFlags(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGLUnmapBufferObject(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGLUnmapBufferObjectAsync(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGLUnregisterBufferObject(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddChildGraphNode(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddDependencies(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddDependencies_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddEmptyNode(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddEventRecordNode(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddEventWaitNode(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddExternalSemaphoresSignalNode(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddExternalSemaphoresWaitNode(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddHostNode(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddKernelNode(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddKernelNode_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddMemAllocNode(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddMemcpyNode(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddMemFreeNode(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddMemsetNode(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddNode(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphAddNode_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphChildGraphNodeGetGraph(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphClone(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphConditionalHandleCreate(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphCreate(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphDebugDotPrint(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphDestroy(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphDestroyNode(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphEventRecordNodeGetEvent(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphEventRecordNodeSetEvent(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphEventWaitNodeGetEvent(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphEventWaitNodeSetEvent(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExecChildGraphNodeSetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExecDestroy(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExecEventRecordNodeSetEvent(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExecEventWaitNodeSetEvent(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExecExternalSemaphoresSignalNodeSetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExecExternalSemaphoresWaitNodeSetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExecGetFlags(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExecHostNodeSetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExecKernelNodeSetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExecKernelNodeSetParams_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExecMemcpyNodeSetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExecMemsetNodeSetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExecNodeSetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExecUpdate(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExecUpdate_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExternalSemaphoresSignalNodeGetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExternalSemaphoresSignalNodeSetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExternalSemaphoresWaitNodeGetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphExternalSemaphoresWaitNodeSetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphGetEdges(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphGetEdges_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphGetNodes(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphGetRootNodes(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphHostNodeGetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphHostNodeSetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsEGLRegisterImage(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsGLRegisterBuffer(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsGLRegisterImage(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsMapResources(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsMapResources_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsResourceGetMappedEglFrame(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsResourceGetMappedMipmappedArray(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsResourceGetMappedPointer(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsResourceGetMappedPointer_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsResourceSetMapFlags(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsResourceSetMapFlags_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsSubResourceGetMappedArray(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsUnmapResources(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsUnmapResources_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsUnregisterResource(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsVDPAURegisterOutputSurface(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphicsVDPAURegisterVideoSurface(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphInstantiate(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphInstantiate_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphInstantiateWithFlags(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphInstantiateWithParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphInstantiateWithParams_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphKernelNodeCopyAttributes(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphKernelNodeGetAttribute(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphKernelNodeGetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphKernelNodeGetParams_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphKernelNodeSetAttribute(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphKernelNodeSetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphKernelNodeSetParams_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphLaunch(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphLaunch_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphMemAllocNodeGetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphMemcpyNodeGetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphMemcpyNodeSetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphMemFreeNodeGetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphMemsetNodeGetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphMemsetNodeSetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphNodeFindInClone(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphNodeGetDependencies(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphNodeGetDependencies_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphNodeGetDependentNodes(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphNodeGetDependentNodes_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphNodeGetEnabled(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphNodeGetType(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphNodeSetEnabled(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphNodeSetParams(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphReleaseUserObject(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphRemoveDependencies(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphRemoveDependencies_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphRetainUserObject(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphUpload(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuGraphUpload_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuImportExternalMemory(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuImportExternalSemaphore(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuIpcCloseMemHandle(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuIpcGetEventHandle(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuIpcGetMemHandle(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuIpcOpenEventHandle(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuIpcOpenMemHandle(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuIpcOpenMemHandle_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuKernelGetAttribute(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuKernelGetFunction(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuKernelGetName(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuKernelGetParamInfo(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuKernelSetAttribute(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuKernelSetCacheConfig(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLaunchCooperativeKernel(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLaunchCooperativeKernelMultiDevice(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLaunchCooperativeKernel_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLaunchHostFunc(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLaunchHostFunc_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLaunchKernelEx_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLaunchKernel_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLibraryEnumerateKernels(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLibraryGetGlobal(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLibraryGetKernel(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLibraryGetKernelCount(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLibraryGetManaged(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLibraryGetModule(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLibraryGetUnifiedFunction(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLibraryLoadData(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLibraryLoadFromFile(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLibraryUnload(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLinkAddData(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLinkAddFile(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuLinkCreate(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemAdvise(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemAdvise_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemAlloc(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemAllocAsync(void) { fprintf(stderr, "[COMPAT_STUB] cuMemAllocAsync CALLED\n");fflush(stderr);return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemAllocAsync_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemAllocFromPoolAsync(void) { fprintf(stderr, "[COMPAT_STUB] cuMemAllocFromPoolAsync CALLED\n");fflush(stderr);return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemAllocFromPoolAsync_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemAllocManaged(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemAllocPitch(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpy(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpy2DAsync(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpy2DAsync_v2_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpy2DUnaligned(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpy2DUnaligned_v2_ptds(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpy3D(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpy3DAsync(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpy3DAsync_v2_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpy3DBatchAsync(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpy3DBatchAsync_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpy3DPeer(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpy3DPeerAsync(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpy3DPeerAsync_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpy3DPeer_ptds(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpy3D_v2_ptds(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpyAsync(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpyAsync_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpyBatchAsync(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpyBatchAsync_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpyDtoD(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpyDtoDAsync(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpyDtoDAsync_v2_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpyDtoD_v2_ptds(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpyDtoH(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpyDtoH_v2_ptds(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpyHtoD(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpyHtoD_v2_ptds(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpyPeer(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpyPeerAsync(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpyPeerAsync_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpyPeer_ptds(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemcpy_ptds(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemFree(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemFreeAsync(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemFreeAsync_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemGetAddressRange(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemGetInfo(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemHostGetDevicePointer(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemHostRegister(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemHostRegister_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemHostUnregister(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemPoolCreate(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemPoolDestroy(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemPoolExportPointer(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemPoolExportToShareableHandle(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemPoolGetAccess(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemPoolGetAttribute(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemPoolImportFromShareableHandle(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemPoolImportPointer(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemPoolSetAccess(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemPoolSetAttribute(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemPoolTrimTo(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemPrefetchAsync(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemPrefetchAsync_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemPrefetchAsync_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemPrefetchAsync_v2_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemRangeGetAttribute(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemRangeGetAttributes(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemsetD2D8(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemsetD2D8Async(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemsetD2D8Async_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemsetD2D8_v2_ptds(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemsetD8(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemsetD8Async(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemsetD8Async_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMemsetD8_v2_ptds(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMipmappedArrayCreate(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMipmappedArrayDestroy(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMipmappedArrayGetLevel(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMipmappedArrayGetMemoryRequirements(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuMipmappedArrayGetSparseProperties(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuModuleGetGlobal(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuModuleGetLoadingMode(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuModuleGetSurfRef(void) { return CUDA_ERROR_NOT_SUPPORTED; }
/* cuPointerGetAttributes: implementada en CudaDr_unified.cpp (2026-07-28). */
__attribute__((visibility("default"))) CUresult cuProfilerInitialize(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuProfilerStart(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuProfilerStop(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuSignalExternalSemaphoresAsync(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuSignalExternalSemaphoresAsync_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamAddCallback(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamAddCallback_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamAttachMemAsync(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamAttachMemAsync_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamBatchMemOp(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamBatchMemOp_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamBeginCapture(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamBeginCapture_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamBeginCaptureToGraph(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamBeginCaptureToGraph_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamBeginCapture_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamBeginCapture_v2_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamCopyAttributes(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamCopyAttributes_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamCreateWithPriority(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamDestroy(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamEndCapture(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamEndCapture_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetAttribute(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetAttribute_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetCaptureInfo(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetCaptureInfo_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetCaptureInfo_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetCaptureInfo_v2_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetCaptureInfo_v3(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetCaptureInfo_v3_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetCtx(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetDevice(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetDevice_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetFlags(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetFlags_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetId(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetId_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetPriority(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamGetPriority_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamIsCapturing(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamIsCapturing_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamQuery_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamSetAttribute(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamSetAttribute_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamSynchronize_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamUpdateCaptureDependencies(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamUpdateCaptureDependencies_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamUpdateCaptureDependencies_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamUpdateCaptureDependencies_v2_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamWaitEvent(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamWaitEvent_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamWaitValue32(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamWaitValue32_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamWaitValue64(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamWaitValue64_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamWriteValue32_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamWriteValue64(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuStreamWriteValue64_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuSurfObjectCreate(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuSurfObjectDestroy(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuSurfObjectGetResourceDesc(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuTexObjectCreate(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuTexObjectDestroy(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuTexObjectGetResourceDesc(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuTexObjectGetResourceViewDesc(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuTexObjectGetTextureDesc(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuThreadExchangeStreamCaptureMode(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuUserObjectCreate(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuUserObjectRelease(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuUserObjectRetain(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuVDPAUCtxCreate(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuVDPAUCtxCreate_v2(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuVDPAUGetDevice(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuWaitExternalSemaphoresAsync(void) { return CUDA_ERROR_NOT_SUPPORTED; }
__attribute__((visibility("default"))) CUresult cuWaitExternalSemaphoresAsync_ptsz(void) { return CUDA_ERROR_NOT_SUPPORTED; }
}
