# docker/conf/spark-defaults.conf

spark.master                                    local[*]
spark.driver.memory                             4g
spark.executor.memory                           4g
spark.serializer                                org.apache.spark.serializer.KryoSerializer
spark.sql.adaptive.enabled                      true
spark.sql.adaptive.coalescePartitions.enabled   true